name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b51afbca5e8f8f1dcf0a68202ee2ceada6b1bbcded5d6a51237ea156a5034dda"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
