name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f0e96a28e1b787ca69bc83d990e47e8bc0f9a7744ac5dae188b3fef8ac8e143"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
