name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee95fa4b1a8cbb02331fba1665408a4b5cd563dfa6bf68619c6cdde940dbe451"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
