name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a1a7d2be4a524d062c0994168cf3f07dee274d1bd3d427c9a79a42d613123b0"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
