name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4728dfc9045b450a4353c8396ec761241d396097736ea62be5a4a583a24299f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
