name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c84cb8a45665d50d5ddad9f8c52ad4616eda6fb87abcbb6c8a7d7d46cc03e2f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
