name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7c7f531ca6a9df97523f2f69d0c2d78ac74f502f9d45816a3f557ed3dda47bc"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
