name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8163e5bf030071c33fe5ddef7e54c87c955273adfe9238dc8afbd62e94546d48"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
