name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eac98030cd44dea414e084933acb8f41479d8894e4a7888f9d2a0cf2c6100430"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
