name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e0d60628475e60f5c126d2910daeab5ff72244dff1b34d8750e5e1018083d69"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
