name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "316cf04d9bee1ec4ea369bc42d97d4ae1e691a1358a3cdb525ba95ba80427f40"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
