name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9213f2e9f70e16aced854ce6003bab99f59af5c6704c812b273b403988b828fb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
