name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7162bf80050d02d74eed4ab0de55499bcbce6451a55ec12ac23c8ddd9d63d123"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.8"]
