name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.6.3"
pack-format = "packwiz:1.1.0"
modrinth-id = "xipWLyHG"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe0941fc05dcbe1f7ae1a9b4ba08f31de83d7f200b669ed0ce08f8aa172fe08a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
