name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd6661bc435b6d1b0592298dc2472e8180ebb80fa3e24ebecc9acfe293d7af85"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
