name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21b1917af4a3a0982a8cd8007731fcdc1c907c7ec5167ded13e95f98bac83a39"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
