name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d2c122f70e112705a50fd351c8498f856aabb26f63b86894b518bc76e2d4d27"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
