name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "458d44aaf7274639da9cbd3606d7876473e2f022e0e8aa7b9962d7551e4ad9c9"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
