name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "967d2b164bcf889d23abad80dc55d22322009cb201892ac93cece5d3285b0c16"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
