name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a8c25c5095d50d2545c5374cbaabfb477328fb8faafda8f9ecf82b347f19cfd"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
