name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e03c3d5cfabb3fbc46c54f860c3eb393f144c3c5ea39f38cfbfe02096c0d5435"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
