name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "478122d1429ad605b893843e4f8c83cf536040cad9e0e7f679f9fca93ea35839"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
