name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "733ca0f94ecb10e31e1285940491bedd136b9e8aaf59e4da7f94cf1627bfe023"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
