name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4745196db9fda39b1f5e580042e1210dcea503bd9264485df83ed269b747e225"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
