name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e866541348b435dbf3a7015568f504d1e8836627b8642ccd7cd61b197471c57a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
