name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.17.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f42c8684d872dd4424e5e565cf8b7e8c1a49ececf3360dd565c3dc6f265e7729"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
