name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "803feb80d182e29b171c5dc4a03b709c07a3f6046ea18b051b32db312ffb947a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6", "1.21.8"]
