name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0012f6a2b8c518bc2bae742c6d1cc842dea16a58b78413abb7957b26719b35e1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
