name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeb99fb3005f2daf1ba91e2c485b74d0cb7465c353793df49cbe29922d0d1203"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
