name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feedf5f258891d57fadb9cfae6648f7743c0601e935eb1fa918f4cc589dc55ee"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
