name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.13.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8272464f5ee54a9216118ebffef2dda147e415edd62ca6882446d0e1e4ffcb34"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
