name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.13.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418fbfb98a25fd470e39a12f2460d4d005c80ccf98e96a105bd12a4fc48ebef7"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
