name = "LCLP's MiniGame Pack"
author = "LCLP"
version = "1.13.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1b809678a60169386bb42c5b839686ee0dae3baa103a3784682dedf8d6ce8c0"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
