name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da405307517b2481269888136cb46cb9e70377ed417dd46a1c332366ef81cbc8"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
