name = "LCLP's Builder Utils Pack"
author = "LCLP"
version = "1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b527b2d84a6b87c9c6e42a06bd3cc7b7d19f21322d806e60d594b0d62d91704"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
